name: bstrong
services:
  db:
    image: mariadb:11.3.2
    container_name: bstrong-db
    environment:
      MYSQL_USER: gymAdmin
      MYSQL_PASSWORD: gymPasswd
      MYSQL_DATABASE: bstrong
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: secure_root_password

    ports:
      - "3306:3306"
    volumes:
      - C:/Users/Th3f0/OneDrive/Desktop/Clase/2025-2026/Acceso a datos/AA1Âºtrimestre/bstrong/mariadb_data:/var/lib/mysql